version: "3.9"
services:
    user-backend:
      container_name: user-backend
      build: ./user/backend
      networks:
        - local-net
      volumes:
        - ./user/backend/app/app/storage:/app/app/storage

    user-frontend:
      extends:
        file: user/docker-compose.yml
        service: user-frontend

    questionnaire-backend:
      container_name: questionnaire-backend
      build: ./questionnaire/backend
      networks:
        - local-net
      volumes:
        - ./questionnaire/backend/app/app/storage:/app/app/storage

    questionnaire-frontend:
      extends:
        file: questionnaire/docker-compose.yml
        service: questionnaire-frontend

    quiz-backend:
      container_name: quiz-backend
      build: ./quiz/backend
      networks:
        - local-net
      volumes:
        - ./quiz/backend/app/app/storage:/app/app/storage

    quiz-frontend:
      extends:
        file: quiz/docker-compose.yml
        service: quiz-frontend


    nginx:
      container_name: nginx
      environment:
        USER_PORT: ${USER_PORT}
        QUESTIONNAIRE_PORT: ${QUESTIONNAIRE_PORT}
        QUIZ_PORT: ${QUIZ_PORT}
      build:
        context: ./nginx
      ports:
        - "${USER_PORT}:${USER_PORT}"
        - "${QUESTIONNAIRE_PORT}:${QUESTIONNAIRE_PORT}"
        - "${QUIZ_PORT}:${QUIZ_PORT}"
      volumes:
        - user-front:/usr/share/nginx/user/
        - questionnaire-front:/usr/share/nginx/questionnaire/
        - quiz-front:/usr/share/nginx/quiz/
      depends_on:
        - user-backend
        - user-frontend
        - questionnaire-backend
        - questionnaire-frontend
        - quiz-backend
        - quiz-frontend
      networks:
        - local-net


volumes:
  user-front:
  questionnaire-front:
  quiz-front:


networks:
  local-net:
    driver: bridge